import Navbar from '@/Components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/Components/footer'
import { Providers } from '@/ReduxState/Providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Yoga and Meditaion',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
    
        <Providers>
              <Navbar />
               {children}
              <Footer />
           </Providers>
        </body>
    </html>
  )
}
